name: BannerBoard
main: me.bigteddy98.bannerboard.BannerBoardPlugin
version: @version@
author: BigTeddy98
commands:
  bannerboard:
  bb:
description: BannerBoard is a lightweight banner board plugin.
softdepend: [ PlaceholderAPI ]
