name: BannerBoard
main: me.bigteddy98.bannerboard.BannerBoardPlugin
version: 1.12.1
api-version: 1.18
author: BigTeddy98
commands:
  bannerboard:
  bb:
description: BannerBoard is a lightweight banner board plugin.
softdepend: [ PlaceholderAPI ]
